### ISSUE TITLE
 SLIDER and PHPBB Styles

### ISSUE THREAD

**Issue by Galixte** [vipaka/phpbb3.1_navbar#2]
Hi @vipaka,

i don’t see the difference between  SLIDER and PHPBB styles.

**Comment by Galixte** [comment]
Hi @vipaka,

could you answer, please ?

**Comment by vipaka** [comment]
PHPBB style has different styling than the slider style, phpbb mimics the phpbb.com menu style (large popout box with inline elements) while slider has 2 horizontal bars, one of which pops out onhover. Both of them need styling improvements.

**Comment by Galixte** [comment]
Thanks you very much for informations !
